package model;

public interface Database {

    public static final String CONNECTION_STRING = "jdbc:derby:data;create=true";

    public static final String CREATE_TABLE_CATEGORIES
            = "CREATE TABLE categories (\n"
            + " id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10),\n"
            + " name VARCHAR(45) NOT NULL,\n"
            + " parent_id INT DEFAULT NULL REFERENCES categories (id),\n"
            + " deleted BOOLEAN NOT NULL DEFAULT false\n"
            + ")";

    public static final String CREATE_TABLE_EXTERNAL_TRANSACTIONS
            = "CREATE TABLE external_transactions (\n"
            + " id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,\n"
            + " name VARCHAR(45) NOT NULL,\n"
            + " amount INT NOT NULL,\n"
            + " date DATE NOT NULL,\n"
            + " category_id INT NOT NULL REFERENCES categories (id),\n"
            + " description VARCHAR(1000) DEFAULT NULL,\n"
            + " regularity_amount INT NOT NULL,\n"
            + " regularity_unit VARCHAR(10) CHECK (regularity_unit IN('FOREVER', 'DAYS', 'WEEKS', 'MONTHS', 'YEARS'))\n"
            + ")";

    public static final String INSERT_MAIN_CATEGORY_INCOME
            = "INSERT INTO categories (id, name, parent_id)\n"
            + "VALUES (1, 'Bevételek', NULL)";

    public static final String INSERT_MAIN_CATEGORY_EXPENSE
            = "INSERT INTO categories (id, name, parent_id)\n"
            + "VALUES (2, 'Kiadások', NULL)";

    public static final String SELECT_CATEGORIES
            = "SELECT *\n"
            + "FROM categories\n"
            + "WHERE deleted = false";

    public static final String SELECT_EXTERNAL_TRANSACTIONS
            = "SELECT *\n"
            + "FROM external_transactions\n"
            + "WHERE 1=1";

    public static final String INSERT_CATEGORY
            = "INSERT INTO categories (\n"
            + " name,\n"
            + " parent_id)\n"
            + "VALUES (?, ?)";

    public static final String INSERT_EXTERNAL_TRANSACTION
            = "INSERT INTO external_transactions (\n"
            + " name,\n"
            + " amount,\n"
            + " date,\n"
            + " category_id,\n"
            + " regularity_amount,\n"
            + " regularity_unit,\n"
            + " description)\n"
            + "VALUES (?, ?, ?, ?, ?, ?, ?)";

    public static final String UPDATE_CATEGORY
            = "UPDATE categories\n"
            + "SET\n"
            + " name = ?,\n"
            + " parent_id = ?\n"
            + "WHERE id = ?";

    public static final String UPDATE_EXTERNAL_TRANSACTION
            = "UPDATE external_transactions\n"
            + "SET\n"
            + " name = ?,\n"
            + " amount = ?,\n"
            + " date = ?,\n"
            + " category_id = ?,\n"
            + " regularity_amount = ?,\n"
            + " regularity_unit = ?,\n"
            + " description = ?\n"
            + "WHERE id = ?";

    public static final String DELETE_CATEGORY
            = "UPDATE categories\n"
            + "SET deleted = true\n"
            + "WHERE id = ?";

    public static final String DELETE_EXTERNAL_TRANSACTION
            = "DELETE FROM external_transactions\n"
            + "WHERE id = ?";
}
